TRAIN:
  DEVICE: "cuda:0"
  MultiGPU: False
  NUM_WORKERS: 2
  LOSS_RATIO: {'kl':0.4,'u':0.01}
  DATASET: "MICROLENS"
  SEED: 2024
  BATCH_SIZE: 64
  MAX_EPOCH: 20
  EARLY_STOP_TURNS: 5
  SAVE_PATH: "ckpt"

TEST:
  BATCH_SIZE: 1024

CHECKPOINTS:
  LOAD_CHECKPOINT: False
  PATH: "ckpt/train_tiktok/checkpoint_1_epoch.pkl"

MODEL:
  MODEL_ID: "UMEPP"
  V_DIM: 768
  T_DIM: 768
  A_DIM: 128
  H_DIM: 512
  DROPOUT: 0.2

OPTIM:
  NAME: "AdamW"
  LR: 1e-4
  WEIGHT_DECAY: 2e-2
  WARMUP_RATE: 0.1

DATASET:
  CONFIG:
    AVAILABLE_TYPE: "TVA"
  MICROLENS:
    DATASET_ID: "microlens"
    PATH: "data/microlens"
  TIKTOK:
    DATASET_ID: "tiktok"
    PATH: "data/tiktok"
  NUS:
    DATASET_ID: "nus"
    PATH: "data/nus"
